export GO111MODULE := on

define run_generator
docker run -u $(shell id -u):$(shell id -g) \
	-v $(CURDIR):/local -w /local \
	openapitools/openapi-generator-cli:v4.3.1 \
	generate -i openapi/covidify.yaml -g go-gin-server -o covidify \
	--global-property models \
	--additional-properties=packageName=models,withGoCodegenComment=true,apiPath=models \
	$(1)
endef

define run_generator_doc
docker run -u $(shell id -u):$(shell id -g) \
	-v $(CURDIR):/local -w /local \
	openapitools/openapi-generator-cli:v4.3.1 \
	generate -i openapi/covidify.yaml -g markdown -o doc \
	$(1)
endef

.PHONY: generate
generate:
	# @$(RM) -rf $(shell grep -l 'Code generated by OpenAPI Generator' covidify/*.go) \
	# 	covidify/go covidify/api covidify/docs
	$(call run_generator)
	# $(call run_generator,-DsupportingFiles=client.go)
	# $(call run_generator,-DsupportingFiles=response.go)
	# $(call run_generator,-DsupportingFiles=configuration.go)
	# $(call run_generator,-DsupportingFiles=README.md)

.PHONY: generate
doc:
	$(call run_generator_doc)
