/*
 * Covidify
 *
 * Simple API collecting guest data.
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"os"
	"strconv"
	"fmt"
	"github.com/fatz/covidify/covidify/server"
	"github.com/namsral/flag"
	log "github.com/sirupsen/logrus"
)

var server *covidify.Server
var config *covidify.Config

func main() {
	config = covidify.NewConfig()
	fs := flag.NewFlagSetWithEnvPrefix(os.Args[0], "COVIDIFY", 0)

	fs.StringVar(&config.CassandraConnection, "cassandra", "127.0.0.1", "comma seperated list of cassandra nodes")
	fs.StringVar(&config.CassandraKeyspace, "keyspace", "covidify", "Cassandra keyspace to be used")
	fs.StringVar(&config.Bind, "bind", "0.0.0.0", "address to bind to")
	fs.IntVar(config.Port, "port", 8080, "port to bind to")

	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
		fs.PrintDefaults()
		os.Exit(1)
	}

	fs.Parse(os.Args[1:])

	if port := os.Getenv("PORT"); port != "" {
		if p, err := strconv.Atoi(port); err == nil {
			log.Infof("$PORT set to %d overwrite config", p)
			config.Port = &p
		} else {
			log.Warnf("$PORT is set to %s unable to parse as port: %s", port, err)
		}
	}

	log.Tracef("Initializing Server with config: %#v", config)
	log.Infof("Initializing Server with config: %#v", config)

	server, err := covidify.NewServerWithConfig(config)
	if err != nil {
		log.Fatalf("Could not initialize Server %v", err)
	}

	log.Info("Server started")
	server.Run()
}
