{
 "title": "Covidify",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingress Req/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"covidify.testing.d2iq.com/\"}[5m]))"
    }
   ]
  },
  {
   "title": "Generators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod) (covidify_generator_request))",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Generator Avg Req time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(covidify_generator_request_response_seconds_sum)/sum(covidify_generator_request_response_seconds_count))"
    }
   ]
  },
  {
   "title": "Covidify API Req/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(gin_requests_total{container=\"api\", namespace=\"covidify\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cleanup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(covidify_clean_success)" },
    { "expr": "covidify_clean_tables" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gin_requests_total[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(covidify_generator_request_response_seconds_bucket{state=\"success\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Covidify API Req/s (by pod)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(gin_requests_total[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Treafik Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "response/sec" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{backend=\"covidify.testing.d2iq.com/\"}[1m])",
     "legendFormat": "{{code}}"
    },
    { "expr": "traefik_" }
   ]
  },
  {
   "title": "Generator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(covidify_generator_request{state=\"success\"}[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(covidify_generator_request{state=\"failure\"}[5m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Visit & Visitors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "visits" }
   ],
   "targets": [
    { "expr": "sum(rate(covidify_visit[5m]))", "legendFormat": "visit/s" },
    {
     "expr": "(sum(covidify_visitors)/sum(covidify_visit))",
     "legendFormat": "visitors/visit"
    }
   ]
  },
  {
   "title": "Cassandra PreparedStatementsExecuted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysq", "legendFormat": "{{task_name}}" }
   ]
  }
 ]
}