# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: covidify-db
#   namespace: covidify
# type: Opaque
# stringData:
#   # TODO: generate passwords
#   root: aMae3ohWah0eeSohtee2pahbe
#   xtrabackup: iew3Aeci7aiw5BohtuoPhaed5
#   monitor: Reil8cuibiphai0ootaS8Ahzi
#   clustercheck: clustercheckpassword
#   proxyadmin: vieD2Xie8veuph8theSil6aeJ
#   pmmserver: bephop2ogetaheu6jaWo9ugix
#   operator: cheinae7Azo3Eil4ohS0eixor


---
apiVersion: pxc.percona.com/v1-7-0
kind: PerconaXtraDBCluster
metadata:
  name: covidify
  namespace: covidify
  finalizers:
    - delete-pxc-pods-in-order
    - delete-proxysql-pvc
    - delete-pxc-pvc
spec:
  crVersion: 1.7.0
  secretsName: covidify-db
  vaultSecretName: covidify-db-vault
  sslSecretName: covidify-db-ssl
  sslInternalSecretName: covidify-db-ssl-internal
  logCollectorSecretName: covidify-db-secrets
#  enableCRValidationWebhook: true
#  tls:
#    SANs:
#      - pxc-1.example.com
#      - pxc-2.example.com
#      - pxc-3.example.com
#    issuerConf:
#      name: special-selfsigned-issuer
#      kind: ClusterIssuer
#      group: cert-manager.io
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: recommended
    schedule: "0 4 * * *"
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.21-12.1
    autoRecovery: true
    resources:
      requests:
        memory: 3G
        cpu: "600m"
        ephemeral-storage: 5Gi
#      limits:
#        memory: 1G
#        cpu: "1"
#        ephemeral-storage: 1Gi
    affinity:
      antiAffinityTopologyKey: "topology.kubernetes.io/zone"
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 500Gi
    gracePeriod: 600
  haproxy:
    enabled: true
    size: 3
    image: percona/percona-xtradb-cluster-operator:1.7.0-haproxy
    resources:
      requests:
        memory: 1G
        cpu: 600m
#      limits:
#        memory: 1G
#        cpu: 700m
    affinity:
      antiAffinityTopologyKey: "topology.kubernetes.io/zone"
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.7.0-logcollector
  pmm:
    enabled: false
    image: percona/pmm-client:2.12.0
    serverHost: monitoring-service.pxc-operator.svc.cluster.local
    serverUser: admin
  backup:
    image: percona/percona-xtradb-cluster-operator:1.7.0-pxc8.0-backup
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 300Gi
    schedule:
      - name: "daily-backup"
        schedule: "0 0 * * *"
        keep: 5
        storageName: fs-pvc
