/*
 * Covidify
 *
 * Simple API collecting guest data.
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type Visit struct {

	Id string `json:"id,omitempty" gorm:"primary_key"`

	TableNumber string `json:"table_number" cql:"table_number"`

	// If not specified it will default to now()
	CheckIn time.Time `json:"check-in,omitempty" gorm:"column:check_in"`

	CheckOut *time.Time `json:"check-out,omitempty" gorm:"column:check_out"`

	Visitors []Visitor `json:"visitors,omitempty" cql:"visitors"`

	Risk VisitRisk `json:"risk,omitempty" cql:"risk"`

	RiskId int64 `json:"risk_id,omitempty"`
}
