FROM golang:alpine as build-env
RUN mkdir /covidify
WORKDIR /covidify
COPY go.mod .
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download
# COPY the source code as the last step
COPY . .

# Build the binary
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /go/bin/hello
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /go/bin/covidify covidify/cmd/covidify/main.go

FROM scratch
ENV GIN_MODE=release
COPY --from=build-env /go/bin/covidify /go/bin/covidify
EXPOSE 8080/tcp
ENTRYPOINT ["/go/bin/covidify"]
