/*
 * Covidify
 *
 * Simple API collecting guest data.
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	sw "github.com/fatz/covidify/covidify/server"
)

func main() {
	log.Printf("Server started")

	s, _ := sw.NewServer()

	s.Run()
}
